steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['ENV_FILE']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$ENV_FILE" >> /root/env_folder/.env
    chmod 400 /root/env_folder/.env
  volumes:
  - name: 'ssh'
    path: /root/env_folder
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:JohanValero/Flask_HelloWorld_GCP.git
  - b develop
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app', './Flask_HelloWorld_GCP/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy', 'flask-app-demo',
    '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app',
    '--region', 'us-central1',
    '--env-vars-file', '/root/env_folder/.env']
  volumes:
  - name: 'ssh'
    path: /root/env_folder
availableSecrets:
  secretManager:
  - versionName: projects/16641413854/secrets/secret-git/versions/2
    env: 'SSH_KEY'
  - versionName: projects/16641413854/secrets/flask_hello_env/versions/latest
    env: 'ENV_FILE'
