steps:
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo ${_SSH_KEY_JV} >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recurse-submodules', 'git@github.com:JohanValero/Flask_HelloWorld_GCP']
  volumes:
  - name: 'ssh'
    path: /root/.ssh