steps:
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recurse-submodules', 'git@github.com:JohanValero/Flask_HelloWorld_GCP']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/secret-git/versions/latest
    env: 'SSH_KEY'